services:
    mmc.postingtemplate.listener:
        class: mmc\postingtemplate\event\main_listener
        arguments:
             - '@template'
             - '@user'
             - '@dbal.conn'
             - '@config'
        tags:
            - { name: event.listener }
